[[redirects]]
from = "/api/*"
to = "https://64bacf97efe05b0d98c698dc--fanciful-gelato-3157a0.netlify.app/.netlify/functions/bundle/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
