[[redirects]]
from = "/api/*"
to = "https://netlify-deploy--aquamarine-vacherin-be3643.netlify.app/.netlify/functions/bundle/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
