[[redirects]]
from="/*"
to="https://netlify-deploy--silver-custard-9195d2.netlify.app/.netlify/functions/bundle/:splat"
status=301
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
